version: '3.8'

services:
  app:
    image: ghcr.io/drewcrx/revup-web:1.0.0
    networks:
      - traefik-public
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"

        # HTTP
        - "traefik.http.routers.revup.entrypoints=http"
        - "traefik.http.routers.revup.rule=Host(`revup.byronrm.com`)"
        - "traefik.http.middlewares.revup-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.middlewares.revup-https-redirect.redirectscheme.permanent=true"
        - "traefik.http.routers.revup.middlewares=revup-https-redirect"

        # HTTPS
        - "traefik.http.routers.revup-secure.entrypoints=https"
        - "traefik.http.routers.revup-secure.rule=Host(`revup.byronrm.com`)"
        - "traefik.http.routers.revup-secure.tls=true"
        - "traefik.http.routers.revup-secure.tls.certresolver=http"
        - "traefik.http.routers.revup-secure.service=revup-app"

        # Puerto interno de Flask
        - "traefik.http.services.revup-app.loadbalancer.server.port=5000"

        # Red de Traefik
        - "traefik.docker.network=traefik-public"

networks:
  traefik-public:
    external: true