name: Publicar RevUp DevOps

on:
  push:
    branches: "main"

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/drewcrx/revup-web:1.0.0

      - name: Mostrar variables básicas
        run: |
          echo "Host: ${{ secrets.VPS_HOST }}"
          echo "Usuario: ${{ secrets.VPS_USER }}"
          echo "Puerto: ${{ secrets.VPS_PORT }}"

      - name: Probar conexión SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            echo "Conexión exitosa"
            touch revup.txt

      - name: Pasar archivos desde git al VPS
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_PORT }}
          source: "stack.yml,Makefile"
          target: "/home/${{ secrets.VPS_USER }}/revup"

      - name: Desplegar stack en el VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd /home/${{ secrets.VPS_USER }}/revup

            echo "==> Descargando la imagen desde GHCR"
            docker pull ghcr.io/drewcrx/revup-web:1.0.0

            echo "==> Desplegando stack"
            docker stack deploy -c stack.yml revup

            echo "==> Estado del stack"
            docker stack services revup